# Generated by Django 3.0.10 on 2020-09-17 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_failedtasknotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldNotification',
            fields=[
                ('notificationbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.NotificationBase')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.notificationbase',),
        ),
        migrations.AddField(
            model_name='notificationbase',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='CreativeWorldNotification',
            fields=[
                ('worldnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.WorldNotification')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.worldnotification',),
        ),
        migrations.CreateModel(
            name='HomeworldNotification',
            fields=[
                ('worldnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.WorldNotification')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.worldnotification',),
        ),
        migrations.CreateModel(
            name='SovereignWorldNotification',
            fields=[
                ('worldnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.WorldNotification')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.worldnotification',),
        ),
    ]
