# Generated by Django 3.0.10 on 2020-09-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_failedtasknotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeWorldNotification',
            fields=[
                ('exoworldnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.ExoworldNotification')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.exoworldnotification',),
        ),
        migrations.CreateModel(
            name='SovereignWorldNotification',
            fields=[
                ('exoworldnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.ExoworldNotification')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.exoworldnotification',),
        ),
    ]
