# Generated by Django 3.0.10 on 2020-09-17 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_creativeworldnotification_sovereignworldnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworldNotification',
            fields=[
                ('exoworldnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.ExoworldNotification')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.exoworldnotification',),
        ),
        migrations.AddField(
            model_name='notificationbase',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
