# Generated by Django 3.1.2 on 2020-10-01 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_forumimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategorySubscription',
            fields=[
                ('subscriptionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.subscriptionbase')),
                ('category_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.subscriptionbase',),
        ),
        migrations.CreateModel(
            name='ForumPMSubscription',
            fields=[
                ('subscriptionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.subscriptionbase')),
                ('pm_recipents', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.subscriptionbase',),
        ),
    ]
