# Generated by Django 3.0.10 on 2020-09-17 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20200917_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldNotification',
            fields=[
                ('notificationbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.NotificationBase')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.notificationbase',),
        ),
        migrations.RemoveField(
            model_name='creativeworldnotification',
            name='exoworldnotification_ptr',
        ),
        migrations.RemoveField(
            model_name='homeworldnotification',
            name='exoworldnotification_ptr',
        ),
        migrations.RemoveField(
            model_name='sovereignworldnotification',
            name='exoworldnotification_ptr',
        ),
        migrations.AddField(
            model_name='creativeworldnotification',
            name='worldnotification_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.WorldNotification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeworldnotification',
            name='worldnotification_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.WorldNotification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sovereignworldnotification',
            name='worldnotification_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.WorldNotification'),
            preserve_default=False,
        ),
    ]
