# Generated by Django 3.1.2 on 2020-10-02 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_forumcategorysubscription_forumpmsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExoworldExpiredNotification',
            fields=[
                ('worldnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.worldnotification')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.worldnotification',),
        ),
    ]
