# Generated by Django 3.1.8 on 2021-04-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20201114_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumimage',
            name='image_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Color'), (1, 'World'), (2, 'World Type'), (3, 'Atmosphere'), (4, 'Misc.'), (5, 'Item')], db_index=True),
        ),
    ]
