# Generated by Django 3.0.8 on 2020-07-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemShopStandPrice',
            fields=[
                ('time', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('location_z', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_count', models.IntegerField()),
                ('beacon_name', models.CharField(db_index=True, max_length=64)),
                ('guild_tag', models.CharField(max_length=8)),
                ('shop_activity', models.IntegerField()),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.World')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.Item')),
            ],
            options={
                'abstract': False,
                'unique_together': {('time', 'world', 'location_x', 'location_y', 'item', 'price', 'item_count')},
            },
        ),
        migrations.CreateModel(
            name='ItemRequestBasketPrice',
            fields=[
                ('time', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('location_z', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_count', models.IntegerField()),
                ('beacon_name', models.CharField(db_index=True, max_length=64)),
                ('guild_tag', models.CharField(max_length=8)),
                ('shop_activity', models.IntegerField()),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.World')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.Item')),
            ],
            options={
                'abstract': False,
                'unique_together': {('time', 'world', 'location_x', 'location_y', 'item', 'price', 'item_count')},
            },
        ),
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE", reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            'ALTER TABLE "boundless_itemshopstandprice" DROP CONSTRAINT "boundless_itemshopstandprice_pkey"', reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "SELECT create_hypertable('boundless_itemshopstandprice', 'time', 'item_id', 4, chunk_time_interval => 86400000000, migrate_data => true, create_default_indexes => false)", reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            'ALTER TABLE "boundless_itemrequestbasketprice" DROP CONSTRAINT "boundless_itemrequestbasketprice_pkey"', reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "SELECT create_hypertable('boundless_itemrequestbasketprice', 'time', 'item_id', 4, chunk_time_interval => 86400000000, migrate_data => true, create_default_indexes => false)", reverse_sql=migrations.RunSQL.noop
        ),
    ]
