# Generated by Django 3.2 on 2021-05-03 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0001_boundless'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='world',
            options={'ordering': ['id'], 'permissions': [('can_view_private', 'Can view private worlds?'), ('is_trusted_user', 'Is trusted editor of world data?')]},
        ),
    ]
