# Generated by Django 3.2.15 on 2022-09-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0003_auto_20210612_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beaconscan',
            name='html_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='base',
            field=models.CharField(blank=True, choices=[('AZURE', 'Azure'), ('CERULEAN', 'Cerulean'), ('COBALT', 'Cobalt'), ('BLUE', 'Blue'), ('LAVENDER', 'Lavender'), ('LILAC', 'Lilac'), ('MAGENTA', 'Magenta'), ('VIOLET', 'Violet'), ('BERRY', 'Berry'), ('FUCHSIA', 'Fuchsia'), ('CHERRY', 'Cherry'), ('RED', 'Red'), ('ROSE', 'Rose'), ('ORANGE', 'Orange'), ('SEPIA', 'Sepia'), ('TAUPE', 'Taupe'), ('MUSTARD', 'Mustard'), ('TAN', 'Tan'), ('YELLOW', 'Yellow'), ('LIME', 'Lime'), ('MOSS', 'Moss'), ('GREEN', 'Green'), ('MINT', 'Mint'), ('TEAL', 'Teal'), ('VIRIDIAN', 'Viridian'), ('TURQUOISE', 'Turquoise'), ('SLATE', 'Slate'), ('BLACK', 'Black')], max_length=16, null=True),
        ),
    ]
