# Generated by Django 3.0.8 on 2020-07-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0003_string_id_creative'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='world',
            name='is_perm',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.CreateModel(
            name='ItemSellRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(default=5)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('state_hash', models.CharField(default='', max_length=128)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.Item')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.World')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemBuyRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(default=5)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('state_hash', models.CharField(default='', max_length=128)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.Item')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.World')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
