# Generated by Django 3.0.8 on 2020-07-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0006_create_worldpoll_timeseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldpoll',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
