# Generated by Django 3.0.8 on 2020-07-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0007_worldpoll_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldpoll',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
