# Generated by Django 3.0.8 on 2020-07-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0009_246_testing_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecount',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Count'),
        ),
    ]
