# Generated by Django 3.0.8 on 2020-07-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0009_testing_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardrecord',
            name='mayor_id',
            field=models.PositiveIntegerField(),
        ),
    ]
