# Generated by Django 3.0.8 on 2020-07-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boundless", "0009_246_testing_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcecount",
            name="count",
            field=models.PositiveIntegerField(verbose_name="Count"),
        ),
        migrations.AlterField(
            model_name="localizedname",
            name="name",
            field=models.CharField(
                db_index=True, max_length=128, verbose_name="Name"
            ),
        ),
    ]
