# Generated by Django 3.0.8 on 2020-07-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0010_name_fixing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='world',
            old_name='creative',
            new_name='is_creative',
        ),
        migrations.RenameField(
            model_name='world',
            old_name='locked',
            new_name='is_locked',
        ),
        migrations.RenameField(
            model_name='world',
            old_name='public',
            new_name='is_public',
        ),
    ]
