# Generated by Django 3.0.8 on 2020-07-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0010_auto_20200727_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizedname',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Name'),
        ),
    ]
