# Generated by Django 3.0.8 on 2020-07-31 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0010_mayor_id_to_int'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_type', models.CharField(choices=[('CHARACTER', 'CHARACTER'), ('CHARACTER_DECAL', 'CHARACTER_DECAL'), ('CREATURE_BASE', 'CREATURE_BASE'), ('CREATURE_AUX', 'CREATURE_AUX'), ('CREATURE_EXOTIC', 'CREATURE_EXOTIC'), ('WOOD', 'WOOD'), ('ROCK', 'ROCK'), ('GRASS', 'GRASS'), ('ICE', 'ICE'), ('GLACIER', 'GLACIER'), ('SOIL', 'SOIL'), ('ASH', 'ASH'), ('GLEAM', 'GLEAM'), ('GRAVEL', 'GRAVEL'), ('GROWTH', 'GROWTH'), ('MOULD', 'MOULD'), ('SAND', 'SAND'), ('SPONGE', 'SPONGE'), ('LEAVES', 'LEAVES'), ('MANTLE', 'MANTLE'), ('MUD', 'MUD'), ('TANGLE', 'TANGLE'), ('THORNS', 'THORNS'), ('FLORA_1', 'FLORA_1'), ('FLORA_DECAL_1', 'FLORA_DECAL_1'), ('FLORA_2', 'FLORA_2'), ('FLORA_DECAL_2', 'FLORA_DECAL_2'), ('FLORA_3', 'FLORA_3'), ('FLORA_DECAL_3', 'FLORA_DECAL_3'), ('FLORA_4', 'FLORA_4'), ('FLORA_DECAL_4', 'FLORA_DECAL_4'), ('INK', 'INK'), ('FIBER', 'FIBER')], max_length=16)),
                ('shade', models.IntegerField()),
                ('base', models.IntegerField()),
                ('hlight', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.Color')),
            ],
        ),
    ]
