# Generated by Django 3.0.8 on 2020-07-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0011_auto_20200728_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldpoll',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
