# Generated by Django 3.0.8 on 2020-07-31 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0011_colorvalue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colorvalue',
            unique_together={('color', 'color_type')},
        ),
        migrations.CreateModel(
            name='WorldCreatureColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creature_type', models.CharField(choices=[('CUTTLETRUNK', 'Cuttletrunk'), ('HOPPER', 'Hopper'), ('HUNTER', 'Hunter'), ('ROADRUNNER', 'Roadrunner'), ('SPITTER', 'Spitter'), ('WILDSTOCK', 'Wildstock')], max_length=16)),
                ('color_data', models.TextField()),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.World')),
            ],
            options={
                'unique_together': {('world', 'creature_type')},
            },
        ),
        migrations.CreateModel(
            name='WorldBlockColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.Color')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.Item')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.World')),
            ],
            options={
                'unique_together': {('world', 'item')},
            },
        ),
    ]
