# Generated by Django 3.0.8 on 2020-08-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0012_world_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='core_liquid',
            field=models.TextField(blank=True, choices=[('lava', 'Lava'), ('water', 'Water')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='surface_liquid',
            field=models.TextField(blank=True, choices=[('lava', 'Lava'), ('water', 'Water')], max_length=5, null=True),
        ),
    ]
