# Generated by Django 3.0.9 on 2020-08-06 00:25

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres import operations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0012_world_updates'),
    ]

    operations = [
        operations.BtreeGinExtension(),
        migrations.AddIndex(
            model_name='world',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='boundless_w_name_97f9a1_gin'),
        ),
        migrations.AddIndex(
            model_name='world',
            index=django.contrib.postgres.indexes.GinIndex(fields=['display_name'], name='boundless_w_display_63cee0_gin'),
        ),
    ]
