# Generated by Django 3.0.8 on 2020-07-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0012_auto_20200731_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='atmosphere_color_b',
            field=models.FloatField(null=True, verbose_name='Atmosphere Linear B Color'),
        ),
        migrations.AlterField(
            model_name='world',
            name='atmosphere_color_g',
            field=models.FloatField(null=True, verbose_name='Atmosphere Linear G Color'),
        ),
        migrations.AlterField(
            model_name='world',
            name='atmosphere_color_r',
            field=models.FloatField(null=True, verbose_name='Atmosphere Linear R Color'),
        ),
        migrations.AlterField(
            model_name='world',
            name='description',
            field=models.CharField(max_length=32, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='world',
            name='is_creative',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='world',
            name='region',
            field=models.CharField(choices=[('use', 'US East'), ('usw', 'US West'), ('euc', 'EU Central'), ('aus', 'Australia'), ('creative', 'Creative')], max_length=16, null=True, verbose_name='Server Region'),
        ),
        migrations.AlterField(
            model_name='world',
            name='size',
            field=models.IntegerField(null=True, verbose_name='World Size'),
        ),
        migrations.AlterField(
            model_name='world',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Placid (1)'), (1, 'Temperate (2)'), (2, 'Rugged (3)'), (3, 'Inhospitable (4)'), (4, 'Turbulent (5)'), (5, 'Fierce (6)'), (6, 'Savage (7)'), (7, 'Brutal (8)')], null=True, verbose_name='Tier'),
        ),
        migrations.AlterField(
            model_name='world',
            name='time_offset',
            field=models.DateTimeField(null=True, verbose_name='Time Offset'),
        ),
        migrations.AlterField(
            model_name='world',
            name='water_color_b',
            field=models.FloatField(null=True, verbose_name='Water Linear B Color'),
        ),
        migrations.AlterField(
            model_name='world',
            name='water_color_g',
            field=models.FloatField(null=True, verbose_name='Water Linear G Color'),
        ),
        migrations.AlterField(
            model_name='world',
            name='water_color_r',
            field=models.FloatField(null=True, verbose_name='Water Linear R Color'),
        ),
        migrations.AlterField(
            model_name='world',
            name='world_type',
            field=models.CharField(choices=[('LUSH', 'Lush'), ('METAL', 'Metal'), ('COAL', 'Coal'), ('CORROSIVE', 'Corrosive'), ('SHOCK', 'Shock'), ('BLAST', 'Blast'), ('TOXIC', 'Toxic'), ('CHILL', 'Chill'), ('BURN', 'Burn'), ('UMBRIS', 'Umbris'), ('RIFT', 'Rift'), ('BLINK', 'Blink')], max_length=9, null=True, verbose_name='World Type'),
        ),
    ]
