# Generated by Django 3.0.8 on 2020-07-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0012_auto_20200728_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboardrecord',
            options={'ordering': ['world_rank']},
        ),
        migrations.AlterModelOptions(
            name='resourcecount',
            options={'ordering': ['-count']},
        ),
    ]
