# Generated by Django 3.0.9 on 2020-08-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0012_world_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='display_name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='world',
            name='end',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='name',
            field=models.CharField(db_index=True, max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='world',
            name='region',
            field=models.CharField(choices=[('use', 'US East'), ('usw', 'US West'), ('euc', 'EU Central'), ('aus', 'Australia'), ('creative', 'Creative')], db_index=True, max_length=16, null=True, verbose_name='Server Region'),
        ),
        migrations.AlterField(
            model_name='world',
            name='start',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Placid (1)'), (1, 'Temperate (2)'), (2, 'Rugged (3)'), (3, 'Inhospitable (4)'), (4, 'Turbulent (5)'), (5, 'Fierce (6)'), (6, 'Savage (7)'), (7, 'Brutal (8)')], db_index=True, null=True, verbose_name='Tier'),
        ),
        migrations.AlterField(
            model_name='world',
            name='world_type',
            field=models.CharField(choices=[('LUSH', 'Lush'), ('METAL', 'Metal'), ('COAL', 'Coal'), ('CORROSIVE', 'Corrosive'), ('SHOCK', 'Shock'), ('BLAST', 'Blast'), ('TOXIC', 'Toxic'), ('CHILL', 'Chill'), ('BURN', 'Burn'), ('UMBRIS', 'Umbris'), ('RIFT', 'Rift'), ('BLINK', 'Blink')], db_index=True, max_length=9, null=True, verbose_name='World Type'),
        ),
    ]
