# Generated by Django 3.0.8 on 2020-08-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0012_world_colors2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='can_be_found',
        ),
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='exist_via_transformation',
        ),
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='new_color',
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='_new_color',
            field=models.NullBooleanField(),
        ),
    ]
