# Generated by Django 3.0.9 on 2020-08-06 01:24

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0013_auto_20200805_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['string_id'], name='boundless_i_string__186db8_gin'),
        ),
        migrations.AddIndex(
            model_name='localizedname',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='boundless_l_name_f8ba51_gin'),
        ),
    ]
