# Generated by Django 3.0.8 on 2020-08-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0013_auto_20200731_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameobj',
            options={'ordering': ['game_id']},
        ),
    ]
