# Generated by Django 3.0.9 on 2020-08-04 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0013_world_filters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worlddistance',
            old_name='world_1',
            new_name='world_source',
        ),
        migrations.AlterField(
            model_name='world',
            name='assignment',
            field=models.ForeignKey(blank=True, help_text='The world this planet orbits, if any', null=True, on_delete=django.db.models.deletion.CASCADE, to='boundless.World'),
        ),
        migrations.AlterField(
            model_name='world',
            name='is_creative',
            field=models.BooleanField(db_index=True, default=False, help_text='If the world is a creative one', null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='If this world is locked (only `true` for Soverign worlds)', null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='If this world is public', null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='region',
            field=models.CharField(choices=[('use', 'US East'), ('usw', 'US West'), ('euc', 'EU Central'), ('aus', 'Australia'), ('creative', 'Creative')], db_index=True, help_text='Server Region', max_length=16, null=True, verbose_name='Server Region'),
        ),
        migrations.AlterField(
            model_name='world',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Placid (1)'), (1, 'Temperate (2)'), (2, 'Rugged (3)'), (3, 'Inhospitable (4)'), (4, 'Turbulent (5)'), (5, 'Fierce (6)'), (6, 'Savage (7)'), (7, 'Brutal (8)')], db_index=True, help_text='Tier of the world. Starts at 0.', null=True, verbose_name='Tier'),
        ),
        migrations.AlterField(
            model_name='worlddistance',
            name='world_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_dest_set', to='boundless.World'),
        ),
    ]
