# Generated by Django 3.0.8 on 2020-08-02 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0013_auto_20200802_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='closest_world',
            field=models.ForeignKey(blank=True, help_text='Closest world to this one. Only populated for Exoworlds', null=True, on_delete=django.db.models.deletion.CASCADE, to='boundless.World'),
        ),
        migrations.AlterField(
            model_name='world',
            name='closest_world_distance',
            field=models.IntegerField(blank=True, help_text='Distance (in blinksecs) to closest world. Only populated for Exoworlds', null=True),
        ),
    ]
