# Generated by Django 3.0.9 on 2020-08-04 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0014_auto_20200804_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worlddistance',
            old_name='world_2',
            new_name='world_dest',
        ),
    ]
