# Generated by Django 3.0.9 on 2020-08-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0014_auto_20200805_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='region',
            field=models.CharField(choices=[('use', 'US East'), ('usw', 'US West'), ('euc', 'EU Central'), ('aus', 'Australia'), ('sandbox', 'Sandbox')], db_index=True, help_text='Server Region', max_length=16, null=True, verbose_name='Server Region'),
        ),
    ]
