# Generated by Django 3.0.8 on 2020-08-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0014_auto_20200802_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='closest_world_distance',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Distance (in blinksecs) to closest world. Only populated for Exoworlds', null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='forum_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
