# Generated by Django 3.0.8 on 2020-08-02 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0014_auto_20200731_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='closest_world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boundless.World'),
        ),
        migrations.AddField(
            model_name='world',
            name='closest_world_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='core_liquid',
            field=models.TextField(blank=True, choices=[('lava', 'Lava'), ('water', 'WATER')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='surface_liquid',
            field=models.TextField(blank=True, choices=[('lava', 'Lava'), ('water', 'WATER')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='can_be_found',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='exist_via_transformation',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='new_color',
            field=models.NullBooleanField(),
        ),
    ]
