# Generated by Django 3.0.8 on 2020-08-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0015_auto_20200802_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='forum_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
