# Generated by Django 3.0.9 on 2020-08-08 12:51

import click
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boundless", "0015_auto_20200806_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcecount",
            name="percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="resourcecount",
            name="percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
