# Generated by Django 3.0.9 on 2020-08-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0016_auto_20200803_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldblockcolor',
            name='_exist_on_perm',
            field=models.NullBooleanField(),
        ),
    ]
