# Generated by Django 3.0.8 on 2020-08-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0016_world_forum_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='world',
            options={'ordering': ['id']},
        ),
    ]
