# Generated by Django 3.0.9 on 2020-08-05 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0016_auto_20200804_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worlddistance',
            name='world_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.World'),
        ),
    ]
