# Generated by Django 3.0.9 on 2020-08-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0018_auto_20200809_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldpollresult',
            name='total_prestige',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Prestige'),
        ),
    ]
