# Generated by Django 3.2 on 2021-05-01 15:44

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import storages.backends.azure_storage


class Migration(migrations.Migration):

    replaces = [('boundless', '0019_auto_20200826_2146'), ('boundless', '0020_delete_forumimage'), ('boundless', '0021_auto_20201003_1438'), ('boundless', '0022_auto_20201004_1143'), ('boundless', '0023_worldblockcolor_created_time'), ('boundless', '0024_auto_20201006_0050'), ('boundless', '0025_auto_20201009_1734'), ('boundless', '0026_auto_20201009_1742'), ('boundless', '0027_auto_20201010_1116'), ('boundless', '0028_auto_20201013_0639'), ('boundless', '0029_auto_20201014_0841'), ('boundless', '0030_resourcecount_fixed_average'), ('boundless', '0031_auto_20201020_1918'), ('boundless', '0032_item_max_stack'), ('boundless', '0033_item_can_be_sold'), ('boundless', '0034_auto_20201022_0654'), ('boundless', '0035_world_map_image'), ('boundless', '0036_auto_20201029_1130'), ('boundless', '0037_auto_20201031_1311'), ('boundless', '0038_auto_20201101_1049'), ('boundless', '0039_auto_20201101_1105'), ('boundless', '0040_item_is_liquid'), ('boundless', '0041_auto_20201101_1130'), ('boundless', '0042_remove_resourcecount_fixed_average'), ('boundless', '0043_auto_20201101_1317'), ('boundless', '0044_item_is_block'), ('boundless', '0045_beacon_beaconplotcolumn_beaconscan'), ('boundless', '0046_auto_20201102_2259_squashed_0061_auto_20210425_1713')]

    dependencies = [
        ('boundless', '0018_auto_20200809_2316'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldpollresult',
            name='total_prestige',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Prestige'),
        ),
        migrations.AddField(
            model_name='world',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='world',
            name='exo_notification_sent',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='itembuyrank',
            name='rank',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='itemsellrank',
            name='rank',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='_days_since_last',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='worldblockcolor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colorvalue',
            name='color_type',
            field=models.CharField(choices=[('CHARACTER', 'CHARACTER'), ('CHARACTER_DECAL', 'CHARACTER_DECAL'), ('CREATURE_BASE', 'CREATURE_BASE'), ('CREATURE_AUX', 'CREATURE_AUX'), ('CREATURE_EXOTIC', 'CREATURE_EXOTIC'), ('WOOD', 'WOOD'), ('ROCK', 'ROCK'), ('GRASS', 'GRASS'), ('ICE', 'ICE'), ('GLACIER', 'GLACIER'), ('SOIL', 'SOIL'), ('ASH', 'ASH'), ('GLEAM', 'GLEAM'), ('GRAVEL', 'GRAVEL'), ('GROWTH', 'GROWTH'), ('MOULD', 'MOULD'), ('SAND', 'SAND'), ('SPONGE', 'SPONGE'), ('LEAVES', 'LEAVES'), ('MANTLE', 'MANTLE'), ('MUD', 'MUD'), ('TANGLE', 'TANGLE'), ('THORNS', 'THORNS'), ('FLORA_1', 'FLORA_1'), ('FLORA_DECAL_1', 'FLORA_DECAL_1'), ('FLORA_2', 'FLORA_2'), ('FLORA_DECAL_2', 'FLORA_DECAL_2'), ('FLORA_3', 'FLORA_3'), ('FLORA_DECAL_3', 'FLORA_DECAL_3'), ('FLORA_4', 'FLORA_4'), ('FLORA_DECAL_4', 'FLORA_DECAL_4'), ('INK', 'INK'), ('FIBER', 'FIBER')], max_length=64),
        ),
        migrations.CreateModel(
            name='LocalizedString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_id', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('gameobj_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boundless.gameobj')),
                ('heat', models.PositiveSmallIntegerField()),
                ('craft_xp', models.PositiveSmallIntegerField()),
                ('machine', models.CharField(choices=[('COMPACTOR', 'COMPACTOR'), ('CRAFTING_TABLE', 'CRAFTING_TABLE'), ('DYE_MAKER', 'DYE_MAKER'), ('EXTRACTOR', 'EXTRACTOR'), ('FURNACE', 'FURNACE'), ('MIXER', 'MIXER'), ('REFINERY', 'REFINERY'), ('WORKBENCH', 'WORKBENCH')], max_length=16, null=True)),
                ('machine_level', models.CharField(blank=True, choices=[('', ''), ('Standard', 'Standard'), ('Powered', 'Powered'), ('Overdriven', 'Overdriven'), ('Supercharged', 'Supercharged')], max_length=16)),
                ('power', models.PositiveIntegerField()),
                ('group_name', models.CharField(max_length=32)),
                ('knowledge_unlock_level', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('boundless.gameobj',),
        ),
        migrations.CreateModel(
            name='RecipeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('display_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.localizedstring')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='mint_value',
            field=models.FloatField(default=0, verbose_name='Chrysominter Value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(choices=[('Attributes', 'Attributes'), ('Basic', 'Basic'), ('Epic', 'Epic')], max_length=16)),
                ('name', models.CharField(max_length=16)),
                ('unlock_level', models.PositiveIntegerField()),
                ('display_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.localizedstring')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_unlocks', models.PositiveIntegerField(help_text='How many times this skill can be unlocked')),
                ('cost', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=32)),
                ('link_type', models.CharField(choices=[('None', 'None'), ('Left', 'Left'), ('Right', 'Right')], max_length=8)),
                ('bundle_prefix', models.CharField(max_length=128)),
                ('affected_by_other_skills', models.BooleanField()),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.localizedstring')),
                ('display_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.localizedstring')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tint_from', to='boundless.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.recipe')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.skill')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(choices=[(0, 'Single'), (1, 'Bulk'), (2, 'Mass')])),
                ('wear', models.PositiveIntegerField()),
                ('spark', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('output_quantity', models.PositiveIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boundless.recipegroup')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boundless.item')),
                ('recipe_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.recipelevel')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.recipegroup')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.item')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.item'),
        ),
        migrations.CreateModel(
            name='LocalizedStringText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=16, verbose_name='Language')),
                ('text', models.TextField()),
                ('string', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.localizedstring')),
            ],
        ),
        migrations.AddIndex(
            model_name='localizedstringtext',
            index=django.contrib.postgres.indexes.GinIndex(fields=['string'], name='boundless_l_string__91275e_gin'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mint_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Chrysominter Value'),
        ),
        migrations.AlterField(
            model_name='localizedstring',
            name='string_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.localizedstring'),
        ),
        migrations.AddField(
            model_name='item',
            name='list_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.localizedstring'),
        ),
        migrations.AddField(
            model_name='skill',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='boundless.skillgroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localizedstringtext',
            name='string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strings', to='boundless.localizedstring'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='skillgroup',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.RemoveField(
            model_name='recipetint',
            name='item',
        ),
        migrations.RemoveField(
            model_name='recipetint',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipeinput',
            name='recipe_level',
        ),
        migrations.RemoveField(
            model_name='recipelevel',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='reciperequirement',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='can_hand_craft',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='tints',
            field=models.ManyToManyField(related_name='_recipe_tints_+', to='boundless.Item'),
        ),
        migrations.AddField(
            model_name='recipegroup',
            name='members',
            field=models.ManyToManyField(to='boundless.Item'),
        ),
        migrations.DeleteModel(
            name='RecipeGroupMember',
        ),
        migrations.DeleteModel(
            name='RecipeTint',
        ),
        migrations.AddField(
            model_name='recipe',
            name='requirements',
            field=models.ManyToManyField(to='boundless.RecipeRequirement'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='levels',
            field=models.ManyToManyField(to='boundless.RecipeLevel'),
        ),
        migrations.AddField(
            model_name='recipelevel',
            name='inputs',
            field=models.ManyToManyField(to='boundless.RecipeInput'),
        ),
        migrations.RemoveIndex(
            model_name='localizedstringtext',
            name='boundless_l_string__91275e_gin',
        ),
        migrations.AddIndex(
            model_name='localizedstringtext',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text'], name='boundless_l_text_aa0532_gin'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='boundless_s_name_a7d57d_gin'),
        ),
        migrations.AddIndex(
            model_name='skillgroup',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='boundless_s_name_7fe673_gin'),
        ),
        migrations.AddField(
            model_name='localizedstringtext',
            name='_plain_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.localizedstring'),
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('image', models.ImageField(storage=storages.backends.azure_storage.AzureStorage(azure_container='local-emoji'), upload_to='')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(storage=storages.backends.azure_storage.AzureStorage(azure_container='local-skills'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='world',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='local-worlds'), upload_to=''),
        ),
        migrations.CreateModel(
            name='EmojiAltName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('emoji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.emoji')),
            ],
        ),
        migrations.RemoveField(
            model_name='world',
            name='description',
        ),
        migrations.RenameField(
            model_name='world',
            old_name='exo_notification_sent',
            new_name='notification_sent',
        ),
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='_days_since_last',
        ),
        migrations.AddField(
            model_name='resourcecount',
            name='_average_per_chunk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='html_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='_exist_on_perm',
        ),
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='_exist_via_transform',
        ),
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='_new_color',
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='first_world',
            field=models.ForeignKey(blank=True, help_text='First non-Exo world with this color', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='boundless.world'),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='is_new',
            field=models.BooleanField(default=False, help_text='This is the first time this WBC has appeared on non-Exo'),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='is_new_transform',
            field=models.BooleanField(default=False, help_text='This is the first time this WBC has been avaiable via transform'),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='last_exo',
            field=models.ForeignKey(blank=True, help_text='Most recent Exo with this color (only for Exo WBCs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='boundless.world'),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='transform_first_world',
            field=models.ForeignKey(blank=True, help_text='First non-Exo WBC that can transform into this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='boundless.world'),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='transform_last_exo',
            field=models.ForeignKey(blank=True, help_text='Most recent Exo WBC that can transform into this one (only for Exo WBCs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='boundless.world'),
        ),
        migrations.AlterField(
            model_name='worldblockcolor',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boundless.world'),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='is_default',
            field=models.BooleanField(default=True, help_text='Is this the color the world spawned with?'),
        ),
        migrations.AlterModelOptions(
            name='worldblockcolor',
            options={'ordering': ['item_id']},
        ),
        migrations.AlterField(
            model_name='item',
            name='string_id',
            field=models.CharField(db_index=True, max_length=64, verbose_name='String ID'),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('gameobj_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boundless.gameobj')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('block_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.item')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('boundless.gameobj',),
        ),
        migrations.CreateModel(
            name='AltItem',
            fields=[
                ('gameobj_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boundless.gameobj')),
                ('name', models.CharField(max_length=64, verbose_name='String ID')),
                ('base_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.item')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('boundless.gameobj',),
        ),
        migrations.AddField(
            model_name='world',
            name='sort_name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='text_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='required_backer_tier',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='required_event',
            field=models.CharField(blank=True, choices=[('GLEAMBOW_RACING', 'Gleambow Racting'), ('CHRISTMAS', 'Christmas'), ('VALENTINES', 'Valentines'), ('HALLOWEEN', 'Halloween'), ('BIRTHDAY', 'Birthday')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='machine',
            field=models.CharField(blank=True, choices=[('COMPACTOR', 'COMPACTOR'), ('CRAFTING_TABLE', 'CRAFTING_TABLE'), ('DYE_MAKER', 'DYE_MAKER'), ('EXTRACTOR', 'EXTRACTOR'), ('FURNACE', 'FURNACE'), ('MIXER', 'MIXER'), ('REFINERY', 'REFINERY'), ('WORKBENCH', 'WORKBENCH')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='machine_level',
            field=models.CharField(blank=True, choices=[('', ''), ('Standard', 'Standard'), ('Powered', 'Powered'), ('Overdriven', 'Overdriven'), ('Supercharged', 'Supercharged')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='recipegroup',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='machine',
            field=models.CharField(blank=True, choices=[('COMPACTOR', 'COMPACTOR'), ('CRAFTING_TABLE', 'CRAFTING_TABLE'), ('DYE_MAKER', 'DYE_MAKER'), ('EXTRACTOR', 'EXTRACTOR'), ('FURNACE', 'FURNACE'), ('MIXER', 'MIXER'), ('REFINERY', 'REFINERY'), ('WORKBENCH', 'WORKBENCH')], db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='is_finalized',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='is_public_claim',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='is_public_edit',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='notification_sent',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='ForumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('game_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boundless.gameobj')),
                ('checksum', models.CharField(max_length=64)),
                ('shortcut_url', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='world',
            name='special_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Color-Cycling')], db_index=True, null=True, verbose_name='Special Type'),
        ),
        migrations.AlterField(
            model_name='world',
            name='active',
            field=models.BooleanField(db_index=True, default=True, help_text='Does this world still exist (returned by game API)?'),
        ),
        migrations.AlterField(
            model_name='worldblockcolor',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this the current color for the world?'),
        ),
        migrations.AddIndex(
            model_name='emoji',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='boundless_e_name_753a14_gin'),
        ),
        migrations.AddIndex(
            model_name='emojialtname',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='boundless_e_name_3fa367_gin'),
        ),
        migrations.AlterModelOptions(
            name='emoji',
            options={},
        ),
        migrations.DeleteModel(
            name='ForumImage',
        ),
        migrations.AddIndex(
            model_name='gameobj',
            index=django.contrib.postgres.indexes.GinIndex(fields=['game_id'], name='boundless_g_game_id_0f0659_gin'),
        ),
        migrations.RemoveIndex(
            model_name='world',
            name='boundless_w_display_63cee0_gin',
        ),
        migrations.AddIndex(
            model_name='world',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_name'], name='boundless_w_text_na_f65d9b_gin'),
        ),
        migrations.AddIndex(
            model_name='world',
            index=django.contrib.postgres.indexes.GinIndex(fields=['id'], name='boundless_w_id_58b1eb_gin'),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worldcreaturecolor',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldcreaturecolor',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='world',
            name='special_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Color-Cycling')], db_index=True, help_text='`1` = Color-Cycling', null=True, verbose_name='Special Type'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='is_boundless_only',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RenameField(
            model_name='resourcecount',
            old_name='_average_per_chunk',
            new_name='average_per_chunk',
        ),
        migrations.AlterField(
            model_name='world',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(0, 'T1 - Placid'), (1, 'T2 - Temperate'), (2, 'T3 - Rugged'), (3, 'T4 - Inhospitable'), (4, 'T5 - Turbulent'), (5, 'T6 - Fierce'), (6, 'T7 - Savage'), (7, 'T8 - Brutal')], db_index=True, help_text='Tier of the world. Starts at 0.', null=True, verbose_name='Tier'),
        ),
        migrations.AlterField(
            model_name='leaderboardrecord',
            name='time',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resourcecount',
            name='time',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worldpollresult',
            name='time',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='itemrequestbasketprice',
            name='beacon_html_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='itemrequestbasketprice',
            name='beacon_text_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='itemshopstandprice',
            name='beacon_html_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='itemshopstandprice',
            name='beacon_text_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardrecord',
            name='html_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardrecord',
            name='text_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='resourcecount',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='item',
            name='can_be_sold',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterUniqueTogether(
            name='itembuyrank',
            unique_together={('item', 'world')},
        ),
        migrations.AlterUniqueTogether(
            name='itemsellrank',
            unique_together={('item', 'world')},
        ),
        migrations.AddField(
            model_name='world',
            name='atlas_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='local-atlas'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='leaderboardrecord',
            name='guild_tag',
            field=models.CharField(max_length=16, verbose_name='Guild Tag'),
        ),
        migrations.AddField(
            model_name='item',
            name='build_xp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='is_resource',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='mine_xp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='prestige',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='max_stack',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='ResourceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_embedded', models.BooleanField()),
                ('exo_only', models.BooleanField(default=False)),
                ('max_tier', models.PositiveSmallIntegerField(choices=[(0, 'T1 - Placid'), (1, 'T2 - Temperate'), (2, 'T3 - Rugged'), (3, 'T4 - Inhospitable'), (4, 'T5 - Turbulent'), (5, 'T6 - Fierce'), (6, 'T7 - Savage'), (7, 'T8 - Brutal')], help_text='Max tier of world to be found on. Starts at 0.', verbose_name='Max Tier')),
                ('min_tier', models.PositiveSmallIntegerField(choices=[(0, 'T1 - Placid'), (1, 'T2 - Temperate'), (2, 'T3 - Rugged'), (3, 'T4 - Inhospitable'), (4, 'T5 - Turbulent'), (5, 'T6 - Fierce'), (6, 'T7 - Savage'), (7, 'T8 - Brutal')], help_text='Min tier of world to be found on. Starts at 0.', verbose_name='Min Tier')),
                ('best_max_tier', models.PositiveSmallIntegerField(choices=[(0, 'T1 - Placid'), (1, 'T2 - Temperate'), (2, 'T3 - Rugged'), (3, 'T4 - Inhospitable'), (4, 'T5 - Turbulent'), (5, 'T6 - Fierce'), (6, 'T7 - Savage'), (7, 'T8 - Brutal')], help_text='Max tier of world to be found on. Starts at 0.', verbose_name='Max Tier')),
                ('best_min_tier', models.PositiveSmallIntegerField(choices=[(0, 'T1 - Placid'), (1, 'T2 - Temperate'), (2, 'T3 - Rugged'), (3, 'T4 - Inhospitable'), (4, 'T5 - Turbulent'), (5, 'T6 - Fierce'), (6, 'T7 - Savage'), (7, 'T8 - Brutal')], help_text='Min tier of world to be found on. Starts at 0.', verbose_name='Min Tier')),
                ('shape', models.PositiveSmallIntegerField()),
                ('size_max', models.PositiveSmallIntegerField()),
                ('size_min', models.PositiveSmallIntegerField()),
                ('altitude_max', models.PositiveSmallIntegerField()),
                ('altitude_min', models.PositiveSmallIntegerField()),
                ('distance_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('distance_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cave_weighting', models.FloatField()),
                ('size_skew_to_min', models.FloatField()),
                ('blocks_above_max', models.PositiveSmallIntegerField()),
                ('blocks_above_min', models.PositiveSmallIntegerField()),
                ('liquid_above_max', models.PositiveSmallIntegerField()),
                ('liquid_above_min', models.PositiveSmallIntegerField()),
                ('noise_frequency', models.FloatField(blank=True, null=True)),
                ('noise_threshold', models.FloatField(blank=True, null=True)),
                ('three_d_weighting', models.FloatField()),
                ('surface_weighting', models.FloatField()),
                ('altitude_best_lower', models.PositiveSmallIntegerField()),
                ('altitude_best_upper', models.PositiveSmallIntegerField()),
                ('distance_best_lower', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('distance_best_upper', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blocks_above_best_lower', models.PositiveSmallIntegerField()),
                ('blocks_above_best_upper', models.PositiveSmallIntegerField()),
                ('liquid_above_best_upper', models.PositiveSmallIntegerField()),
                ('liquid_above_best_lower', models.PositiveSmallIntegerField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource_data', to='boundless.item')),
                ('liquid_favorite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.item')),
                ('liquid_second_favorite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.item')),
                ('surface_favorite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.item')),
                ('surface_second_favorite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.item')),
            ],
        ),
        migrations.CreateModel(
            name='Liquid',
            fields=[
                ('gameobj_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boundless.gameobj')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('block_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.item')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('boundless.gameobj',),
        ),
        migrations.AddField(
            model_name='item',
            name='is_liquid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ResourceDataBestWorld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_type', models.CharField(choices=[('LUSH', 'Lush'), ('METAL', 'Metal'), ('COAL', 'Coal'), ('CORROSIVE', 'Corrosive'), ('SHOCK', 'Shock'), ('BLAST', 'Blast'), ('TOXIC', 'Toxic'), ('CHILL', 'Chill'), ('BURN', 'Burn'), ('DARKMATTER', 'Umbris'), ('RIFT', 'Rift'), ('BLINK', 'Blink')], max_length=10, verbose_name='World Type')),
                ('data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_worlds', to='boundless.resourcedata')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='is_block',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('time', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('is_campfire', models.BooleanField()),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('location_z', models.IntegerField()),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.world')),
            ],
            options={
                'unique_together': {('time', 'world', 'location_x', 'location_y', 'location_z')},
            },
        ),
        migrations.CreateModel(
            name='BeaconScan',
            fields=[
                ('time', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('mayor_name', models.CharField(max_length=64)),
                ('prestige', models.PositiveIntegerField(blank=True, null=True)),
                ('compactness', models.SmallIntegerField(blank=True, null=True)),
                ('num_plots', models.PositiveIntegerField(blank=True, null=True)),
                ('num_columns', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.beacon')),
            ],
            options={
                'unique_together': {('time', 'beacon')},
            },
        ),
        migrations.CreateModel(
            name='BeaconPlotColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_x', models.IntegerField()),
                ('plot_z', models.IntegerField()),
                ('count', models.PositiveSmallIntegerField()),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.beacon')),
            ],
            options={
                'unique_together': {('beacon', 'plot_x', 'plot_z')},
            },
        ),
        migrations.RunSQL(
            sql='ALTER TABLE "boundless_beaconscan" DROP CONSTRAINT "boundless_beaconscan_pkey"',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql="SELECT create_hypertable('boundless_beaconscan', 'time', chunk_time_interval => 86400000000, migrate_data => true, create_default_indexes => false)",
            reverse_sql='',
        ),
        migrations.AddField(
            model_name='beaconscan',
            name='text_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='beaconscan',
            name='html_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.RemoveField(
            model_name='emoji',
            name='is_boundless_only',
        ),
        migrations.AddField(
            model_name='emoji',
            name='category',
            field=models.CharField(blank=True, choices=[('SMILEY', 'Smiley & Emotion'), ('PEOPLE', 'People & Body'), ('COMPONENT', 'Component'), ('ANIMAL', 'Animals & Nature'), ('FOOD', 'Food & Drink'), ('TRAVEL', 'Travel & Places'), ('ACTIVITIES', 'Activities'), ('OBJECTS', 'Objects'), ('SYMBOLS', 'Symbols'), ('FLAGS', 'Flags'), ('BOUNDLESS', 'Boundless'), ('UNCATEGORIZED', 'Uncategorized')], db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='itemrequestbasketprice',
            name='guild_tag',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='itemshopstandprice',
            name='guild_tag',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterModelOptions(
            name='world',
            options={'ordering': ['id'], 'permissions': [('can_view_private', 'Can view private worlds?')]},
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='local-items'), upload_to=''),
        ),
        migrations.AddField(
            model_name='emoji',
            name='image_small',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='local-emoji'), upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='image_small',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='local-items'), upload_to=''),
        ),
        migrations.CreateModel(
            name='ItemColorVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=storages.backends.azure_storage.AzureStorage(azure_container='local-items'), upload_to='')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.color')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.item')),
                ('image_small', models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='local-items'), upload_to='')),
            ],
            options={
                'unique_together': {('item', 'color')},
            },
        ),
        migrations.AddField(
            model_name='world',
            name='image_small',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='local-worlds'), upload_to=''),
        ),
        migrations.CreateModel(
            name='ItemMetalVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=storages.backends.azure_storage.AzureStorage(azure_container='local-items'), upload_to='')),
                ('image_small', models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='local-items'), upload_to='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.item')),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.metal')),
            ],
            options={
                'unique_together': {('item', 'metal')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='default_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boundless.color'),
        ),
        migrations.AddField(
            model_name='world',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.IntegerField()),
                ('location_z', models.IntegerField()),
                ('prestige', models.PositiveIntegerField(db_index=True, default=None)),
                ('name', models.CharField(default=None, max_length=64)),
                ('text_name', models.CharField(blank=True, max_length=64, null=True)),
                ('html_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.world')),
            ],
            options={
                'unique_together': set(),
            },
        ),
    ]
