# Generated by Django 3.0.9 on 2020-08-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0019_auto_20200826_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
