# Generated by Django 3.1.1 on 2020-09-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0019_auto_20200826_2146_squashed_0048_auto_20200930_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumimage',
            name='checksum',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='forumimage',
            name='shortcut_url',
            field=models.CharField(max_length=64),
        ),
    ]
