# Generated by Django 3.1.1 on 2020-10-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0019_auto_20200826_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForumImage',
        ),
    ]
