# Generated by Django 3.0.9 on 2020-08-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0020_world_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='exo_notification_sent',
            field=models.NullBooleanField(),
        ),
    ]
