# Generated by Django 3.1.1 on 2020-09-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0020_auto_20200930_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='special_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Color-Cycling')], db_index=True, null=True, verbose_name='Special Type'),
        ),
    ]
