# Generated by Django 3.1.2 on 2020-10-03 18:38

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0020_delete_forumimage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gameobj',
            index=django.contrib.postgres.indexes.GinIndex(fields=['game_id'], name='boundless_g_game_id_0f0659_gin'),
        ),
    ]
