# Generated by Django 3.1.1 on 2020-10-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0021_world_special_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='active',
            field=models.BooleanField(db_index=True, default=True, help_text='Does this world still exist (returned by game API)?'),
        ),
        migrations.AlterField(
            model_name='worldblockcolor',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this the current color for the world?'),
        ),
    ]
