# Generated by Django 3.1.2 on 2020-10-04 15:43

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0021_auto_20201003_1438'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='world',
            name='boundless_w_display_63cee0_gin',
        ),
        migrations.AddIndex(
            model_name='world',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_name'], name='boundless_w_text_na_f65d9b_gin'),
        ),
        migrations.AddIndex(
            model_name='world',
            index=django.contrib.postgres.indexes.GinIndex(fields=['id'], name='boundless_w_id_58b1eb_gin'),
        ),
    ]
