# Generated by Django 3.0.9 on 2020-08-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0021_world_exo_notification_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembuyrank',
            name='rank',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='itemsellrank',
            name='rank',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
