# Generated by Django 3.0.9 on 2020-08-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0022_auto_20200831_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldblockcolor',
            name='_days_since_last',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
