# Generated by Django 3.1.1 on 2020-10-01 14:20

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0022_auto_20201001_0937'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emoji',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='boundless_e_name_753a14_gin'),
        ),
        migrations.AddIndex(
            model_name='emojialtname',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='boundless_e_name_3fa367_gin'),
        ),
    ]
