# Generated by Django 3.1.2 on 2020-10-06 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0022_auto_20201004_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldblockcolor',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
