# Generated by Django 3.0.9 on 2020-09-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0023_worldblockcolor__days_since_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldblockcolor',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='worldblockcolor',
            unique_together=set(),
        ),
    ]
