# Generated by Django 3.1.1 on 2020-10-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0023_auto_20201001_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emoji',
            options={},
        ),
    ]
