# Generated by Django 3.1.2 on 2020-10-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0024_auto_20201006_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='is_game_emoji',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='world',
            name='special_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Color-Cycling')], db_index=True, help_text='`1` = Color-Cycling', null=True, verbose_name='Special Type'),
        ),
    ]
