# Generated by Django 3.0.9 on 2020-09-02 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0024_auto_20200902_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldblockcolor',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
