# Generated by Django 3.1.2 on 2020-10-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0025_auto_20201009_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emoji',
            name='is_game_emoji',
        ),
        migrations.AddField(
            model_name='emoji',
            name='is_boundless_only',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
