# Generated by Django 3.1.2 on 2020-10-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0027_auto_20201010_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecount',
            name='fixed_average',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='world',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(0, 'T1 - Placid'), (1, 'T2 - Temperate'), (2, 'T3 - Rugged'), (3, 'T4 - Inhospitable'), (4, 'T5 - Turbulent'), (5, 'T6 - Fierce'), (6, 'T7 - Savage'), (7, 'T8 - Brutal')], db_index=True, help_text='Tier of the world. Starts at 0.', null=True, verbose_name='Tier'),
        ),
    ]
