# Generated by Django 3.0.10 on 2020-09-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0027_skills_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
