# Generated by Django 3.0.10 on 2020-09-13 16:39

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0027_skills_recipes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='localizedstringtext',
            name='boundless_l_string__91275e_gin',
        ),
        migrations.AddIndex(
            model_name='localizedstringtext',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text'], name='boundless_l_text_aa0532_gin'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='boundless_s_name_a7d57d_gin'),
        ),
        migrations.AddIndex(
            model_name='skillgroup',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='boundless_s_name_7fe673_gin'),
        ),
    ]
