# Generated by Django 3.0.10 on 2020-09-15 13:31

from django.db import migrations, models
import storages.backends.azure_storage


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0027_skills_recipes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emoji',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='emoji',
            name='image',
            field=models.ImageField(storage=storages.backends.azure_storage.AzureStorage(azure_container='local-emoji'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(storage=storages.backends.azure_storage.AzureStorage(azure_container='local-skills'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='world',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='local-worlds'), upload_to=''),
        ),
    ]
