# Generated by Django 3.0.10 on 2020-09-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0028_auto_20200913_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizedstringtext',
            name='_plain_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
