# Generated by Django 3.1.2 on 2020-10-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0028_auto_20201013_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcecount',
            name='fixed_average',
        ),
        migrations.AlterField(
            model_name='leaderboardrecord',
            name='time',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resourcecount',
            name='time',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worldpollresult',
            name='time',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
