# Generated by Django 3.0.10 on 2020-09-14 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0029_localizedstringtext__plain_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.LocalizedString'),
        ),
    ]
