# Generated by Django 3.1.2 on 2020-10-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0029_auto_20201014_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecount',
            name='fixed_average',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
