# Generated by Django 3.0.10 on 2020-09-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0029_emojialtname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world',
            name='description',
        ),
    ]
