# Generated by Django 3.1.2 on 2020-10-20 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0030_resourcecount_fixed_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequestbasketprice',
            name='beacon_html_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='itemrequestbasketprice',
            name='beacon_text_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='itemshopstandprice',
            name='beacon_html_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='itemshopstandprice',
            name='beacon_text_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardrecord',
            name='html_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardrecord',
            name='text_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='resourcecount',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
