# Generated by Django 3.0.10 on 2020-09-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0030_remove_world_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='world',
            old_name='exo_notification_sent',
            new_name='notification_sent',
        ),
    ]
