# Generated by Django 3.0.10 on 2020-09-19 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0031_auto_20200917_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='_days_since_last',
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='_days_since_last_exo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='_exist_via_exo_transform',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='_last_exo_world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.World'),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='_new_exo_color',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='_sovereign_only',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='_via_exo_transform_world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.World'),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='_via_transform_world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.World'),
        ),
    ]
