# Generated by Django 3.1.2 on 2020-10-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0031_auto_20201020_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='max_stack',
            field=models.IntegerField(default=100),
        ),
    ]
