# Generated by Django 3.0.10 on 2020-09-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0032_auto_20200919_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecount',
            name='_average_per_chunk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
