# Generated by Django 3.1.2 on 2020-10-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0032_item_max_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='can_be_sold',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
