# Generated by Django 3.1.2 on 2020-10-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0033_item_can_be_sold'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itembuyrank',
            unique_together={('item', 'world')},
        ),
        migrations.AlterUniqueTogether(
            name='itemsellrank',
            unique_together={('item', 'world')},
        ),
    ]
