# Generated by Django 3.0.10 on 2020-09-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0033_resourcecount__average_per_chunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecount',
            name='_average_per_chunk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
