# Generated by Django 3.0.10 on 2020-09-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0034_auto_20200919_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='_html_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='_first_world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.World'),
        ),
    ]
