# Generated by Django 3.1.2 on 2020-10-29 15:29

from django.db import migrations, models
import storages.backends.azure_storage


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0034_auto_20201022_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='map_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='local-atlas'), upload_to=''),
        ),
    ]
