# Generated by Django 3.0.10 on 2020-09-19 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0035_auto_20200919_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='_days_since_last_exo',
        ),
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='_exist_on_perm',
        ),
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='_exist_via_exo_transform',
        ),
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='_exist_via_transform',
        ),
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='_first_world',
        ),
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='_last_exo_world',
        ),
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='_new_color',
        ),
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='_new_exo_color',
        ),
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='_sovereign_only',
        ),
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='_via_exo_transform_world',
        ),
        migrations.RemoveField(
            model_name='worldblockcolor',
            name='_via_transform_world',
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='default',
            field=models.BooleanField(default=True, help_text='Is this the color the world spawned with?'),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='first_world',
            field=models.ForeignKey(blank=True, help_text='First non-Exo world with this color', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='boundless.World'),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='is_new',
            field=models.BooleanField(default=False, help_text='This is the first time this WBC has appeared on non-Exo'),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='is_new_transform',
            field=models.BooleanField(default=False, help_text='This is the first time this WBC has been avaiable via transform'),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='last_exo',
            field=models.ForeignKey(blank=True, help_text='Most recent Exo with this color (only for Exo WBCs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='boundless.World'),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='transform_first_world',
            field=models.ForeignKey(blank=True, help_text='First non-Exo WBC that can transform into this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='boundless.World'),
        ),
        migrations.AddField(
            model_name='worldblockcolor',
            name='transform_last_exo',
            field=models.ForeignKey(blank=True, help_text='Most recent Exo WBC that can transform into this one (only for Exo WBCs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='boundless.World'),
        ),
        migrations.AlterField(
            model_name='worldblockcolor',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boundless.World'),
        ),
    ]
