# Generated by Django 3.1.2 on 2020-10-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0036_auto_20201029_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardrecord',
            name='guild_tag',
            field=models.CharField(max_length=16, verbose_name='Guild Tag'),
        ),
    ]
