# Generated by Django 3.0.10 on 2020-09-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0036_auto_20200919_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
