# Generated by Django 3.0.10 on 2020-09-20 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0037_emoji_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldblockcolor',
            old_name='default',
            new_name='is_default',
        ),
    ]
