# Generated by Django 3.0.10 on 2020-09-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0038_auto_20200919_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worldblockcolor',
            options={'ordering': ['item_id']},
        ),
    ]
