# Generated by Django 3.1.2 on 2020-11-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0038_auto_20201101_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_resource',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
