# Generated by Django 3.0.10 on 2020-09-21 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0039_auto_20200919_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='string_id',
            field=models.CharField(db_index=True, max_length=64, verbose_name='String ID'),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('gameobj_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boundless.GameObj')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('block_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.Item')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('boundless.gameobj',),
        ),
        migrations.CreateModel(
            name='AltItem',
            fields=[
                ('gameobj_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boundless.GameObj')),
                ('name', models.CharField(max_length=64, verbose_name='String ID')),
                ('base_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boundless.Item')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('boundless.gameobj',),
        ),
    ]
