# Generated by Django 3.1.2 on 2020-11-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0039_auto_20201101_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_liquid',
            field=models.BooleanField(default=False),
        ),
    ]
