# Generated by Django 3.1.2 on 2020-11-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0040_item_is_liquid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_liquid',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
