# Generated by Django 3.0.10 on 2020-09-22 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0040_auto_20200921_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('game_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boundless.GameObj')),
            ],
        ),
    ]
