# Generated by Django 3.0.10 on 2020-09-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0041_forumimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumimage',
            name='checksum',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
