# Generated by Django 3.1.2 on 2020-11-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0041_auto_20201101_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcecount',
            name='fixed_average',
        ),
    ]
