# Generated by Django 3.0.10 on 2020-09-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0043_forumimage_shortcut_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='world',
            old_name='_html_name',
            new_name='html_name',
        ),
        migrations.AddField(
            model_name='world',
            name='is_public_claim',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='world',
            name='is_public_edit',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='world',
            name='sort_name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='text_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
