# Generated by Django 3.1.2 on 2020-11-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0043_auto_20201101_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_block',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
