# Generated by Django 3.0.10 on 2020-09-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0044_auto_20200924_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='is_finalized',
            field=models.NullBooleanField(),
        ),
    ]
