# Generated by Django 3.0.10 on 2020-09-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0045_world_is_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='required_backer_tier',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='required_event',
            field=models.CharField(blank=True, choices=[('GLEAMBOW_RACING', 'Gleambow Racting'), ('CHRISTMAS', 'Christmas'), ('VALENTINES', 'Valentines'), ('HALLOWEEN', 'Halloween'), ('BIRTHDAY', 'Birthday')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='machine',
            field=models.CharField(blank=True, choices=[('COMPACTOR', 'COMPACTOR'), ('CRAFTING_TABLE', 'CRAFTING_TABLE'), ('DYE_MAKER', 'DYE_MAKER'), ('EXTRACTOR', 'EXTRACTOR'), ('FURNACE', 'FURNACE'), ('MIXER', 'MIXER'), ('REFINERY', 'REFINERY'), ('WORKBENCH', 'WORKBENCH')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='machine_level',
            field=models.CharField(blank=True, choices=[('', ''), ('Standard', 'Standard'), ('Powered', 'Powered'), ('Overdriven', 'Overdriven'), ('Supercharged', 'Supercharged')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='recipegroup',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
