# Generated by Django 3.1.2 on 2020-11-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0046_auto_20201102_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beaconscan',
            name='html_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
