# Generated by Django 3.0.10 on 2020-09-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0046_auto_20200928_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='machine',
            field=models.CharField(blank=True, choices=[('COMPACTOR', 'COMPACTOR'), ('CRAFTING_TABLE', 'CRAFTING_TABLE'), ('DYE_MAKER', 'DYE_MAKER'), ('EXTRACTOR', 'EXTRACTOR'), ('FURNACE', 'FURNACE'), ('MIXER', 'MIXER'), ('REFINERY', 'REFINERY'), ('WORKBENCH', 'WORKBENCH')], db_index=True, max_length=16, null=True),
        ),
    ]
