# Generated by Django 3.1.1 on 2020-09-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0047_auto_20200928_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='is_finalized',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='is_public_claim',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='is_public_edit',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='notification_sent',
            field=models.BooleanField(null=True),
        ),
    ]
