# Generated by Django 3.1.2 on 2020-11-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0047_auto_20201102_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emoji',
            name='is_boundless_only',
        ),
        migrations.AddField(
            model_name='emoji',
            name='category',
            field=models.CharField(blank=True, choices=[('SMILEY', 'Smiley & Emotion'), ('PEOPLE', 'People & Body'), ('COMPONENT', 'Component'), ('ANIMAL', 'Animals & Nature'), ('FOOD', 'Food & Drink'), ('TRAVEL', 'Travel & Places'), ('ACTIVITES', 'Activies'), ('OBJECTS', 'Objects'), ('SYMBOLS', 'Symbols'), ('FLAGS', 'Flags'), ('BOUNDLESS', 'Boundless')], db_index=True, max_length=16, null=True),
        ),
    ]
