# Generated by Django 3.1.2 on 2020-11-04 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0050_auto_20201104_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.IntegerField()),
                ('location_z', models.IntegerField()),
                ('prestige', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('text_name', models.CharField(blank=True, max_length=64, null=True)),
                ('html_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.world')),
            ],
            options={
                'unique_together': {('world', 'location_x', 'location_z')},
            },
        ),
    ]
