# Generated by Django 3.1.2 on 2020-11-04 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0051_settlement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settlement',
            unique_together=set(),
        ),
    ]
