# Generated by Django 3.1.2 on 2020-11-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0052_auto_20201104_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='html_name',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settlement',
            name='name',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settlement',
            name='prestige',
            field=models.PositiveIntegerField(db_index=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settlement',
            name='text_name',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
