# Generated by Django 3.1.2 on 2021-03-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0053_auto_20201104_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequestbasketprice',
            name='guild_tag',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='itemshopstandprice',
            name='guild_tag',
            field=models.CharField(max_length=16),
        ),
    ]
