# Generated by Django 3.1.2 on 2021-03-31 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0054_auto_20210327_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='world',
            options={'ordering': ['id'], 'permissions': [('can_view_private', 'Can view private worlds?')]},
        ),
    ]
