# Generated by Django 3.1.8 on 2021-04-13 22:37

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.azure_storage


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0055_can_view_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='local-items'), upload_to=''),
        ),
        migrations.CreateModel(
            name='ItemColorVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=storages.backends.azure_storage.AzureStorage(azure_container='local-items'), upload_to='')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.color')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.item')),
            ],
            options={
                'unique_together': {('item', 'color')},
            },
        ),
    ]
