# Generated by Django 3.1.8 on 2021-04-15 18:57

from django.db import migrations, models
import storages.backends.azure_storage


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0056_auto_20210413_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='image_small',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='local-emoji'), upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='image_small',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='local-items'), upload_to=''),
        ),
        migrations.AddField(
            model_name='itemcolorvariant',
            name='image_small',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='local-items'), upload_to=''),
        ),
        migrations.AddField(
            model_name='world',
            name='image_small',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='local-worlds'), upload_to=''),
        ),
    ]
