# Generated by Django 3.1.8 on 2021-04-16 14:41

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.azure_storage


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0057_auto_20210415_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMetalVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=storages.backends.azure_storage.AzureStorage(azure_container='local-items'), upload_to='')),
                ('image_small', models.ImageField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='local-items'), upload_to='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.item')),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boundless.metal')),
            ],
            options={
                'unique_together': {('item', 'metal')},
            },
        ),
    ]
