# Generated by Django 3.1.8 on 2021-04-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0058_itemmetalvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='default_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boundless.color'),
        ),
    ]
