# Generated by Django 3.1.8 on 2021-04-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0059_item_default_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
