version: '3.4'

services:
  django: &django
    build:
      cache_from:
      - docker.pkg.github.com/AngellusMortis/bge/build-cache-django
      - bge_dev_django

  lint:
    <<: *django

  test:
    <<: *django

  postgres:
    build:
      cache_from:
      - docker.pkg.github.com/AngellusMortis/bge/build-cache-postgres
      - bge_postgres
