version: '3.4'

services:
    django: &django
    ## enable .env.local file
      env_file:
        - ./.env
        - ./.env.local
      ports:
        - "9000:8000"
      volumes:
        - .:/app
        ## Replace with path your Boundless install
        - C:\Program Files\Steam\steamapps\common\Boundless:/boundless

    manage:
      <<: *django
      ports: []

    test:
      <<: *django
      ports: []

    lint:
      <<: *django
      ports: []

    format:
      <<: *django
      ports: []

    celery:
      <<: *django
      ports: []

    celerybeat:
      <<: *django
      ports: []

    flower:
      <<: *django
      ports:
        - "6555:5555"
