services:
    django: &django
    ## enable .local.env file
      env_file:
        - ./.env
        - ./.local.env
      ports:
        - "28000:8000"
      volumes:
        - .:/app
        ## Replace with path to your Boundless install
        - C:\Program Files\Steam\steamapps\common\Boundless:/boundless
        ## Replace with path to you out folder for `boundless_icon_render`
        - /path/to/boundless_icon_render/out:/boundless-icons

    manage:
      <<: *django
      ports: []

    test:
      <<: *django
      ports: []

    lint:
      <<: *django
      ports: []

    format:
      <<: *django
      ports: []

    celery:
      <<: *django
      ports: []

    celerybeat:
      <<: *django
      ports: []

    postgres:
    ## enable .local.env file
      env_file:
        - ./.env
        - ./.local.env
