version: '3.4'

services:
    django: &django
    ## enable .local.env file
      env_file:
        - ./.env
        - ./.local.env
      ports:
        - "9000:8000"
      volumes:
        - .:/app
        ## Replace with path to your Google Service Account credentials
        - ./path/to/crednetials.json:/home/django/.config/gspread/service_account.json
        ## Replace with path your Boundless install
        - C:\Program Files\Steam\steamapps\common\Boundless:/boundless

    manage:
      <<: *django
      ports: []

    test:
      <<: *django
      ports: []

    lint:
      <<: *django
      ports: []

    format:
      <<: *django
      ports: []

    celery:
      <<: *django
      ports: []

    celerybeat:
      <<: *django
      ports: []

    flower:
      <<: *django
      ports:
        - "6555:5555"

    postgres:
    ## enable .local.env file
      env_file:
        - ./.env
        - ./.local.env

    # Add celery-exporter
    # celery-exporter:
    #   image: ovalmoney/celery-exporter
