[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | .*migrations.*
    | versioneer.py
  )
)
'''

[tool.coverage.run]
include = [
  'boundlexx/*',
]
omit = [
  '*migrations*',
  '*tests*',
]
plugins = [
  'django_coverage_plugin',
]


[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
sections = [
  "FUTURE",
  "STDLIB",
  "THIRDPARTY",
  "FIRSTPARTY",
  "LOCALFOLDER",
]
skip = [
  ".tox",
  ".git",
  "*/migrations/*",
  "*/static/CACHE/*",
  "docs",
  "node_modules",
  "manage.py",
]

[tool.pylint.master]
load-plugins = [
  'pylint_django',
  'pylint_celery'
]

[tool.pylint.format]
max-line = 80

[tool.pylint.messages_control]
disable = [
  'too-few-public-methods',
  'no-self-use',
  'missing-docstring',
  'invalid-name',
  'bad-continuation',
  'line-too-long',
  'unused-argument',
  'useless-super-delegation',
  'duplicate-code',
]

[tool.pylint.design]
max-parents = 13

[tool.pylint.typecheck]
generated-members = [
  'REQUEST',
  'acl_users',
  'aq_parent',
  '[a-zA-Z]+_set{1,2}',
  'save',
  'delete',
]

[tool.pytest.ini_options]
addopts = "--ds=config.settings.test --reuse-db --cov-report xml --cov-report term:skip-covered --cov=boundlexx"
python_files = "tests.py test_*.py"
env_override_existing_values = 1
env_files= '.test.env'
