# Generated by Django 3.0.8 on 2020-07-21 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameObj",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Active"),
                ),
                (
                    "game_id",
                    models.IntegerField(db_index=True, verbose_name="Game ID"),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_boundless.gameobj_set+",
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
            options={"unique_together": {("game_id", "polymorphic_ctype")},},
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "gameobj_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="boundless.GameObj",
                    ),
                ),
            ],
            options={"abstract": False, "base_manager_name": "objects",},
            bases=("boundless.gameobj",),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "gameobj_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="boundless.GameObj",
                    ),
                ),
            ],
            options={"abstract": False, "base_manager_name": "objects",},
            bases=("boundless.gameobj",),
        ),
        migrations.CreateModel(
            name="Metal",
            fields=[
                (
                    "gameobj_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="boundless.GameObj",
                    ),
                ),
            ],
            options={"abstract": False, "base_manager_name": "objects",},
            bases=("boundless.gameobj",),
        ),
        migrations.CreateModel(
            name="Subtitle",
            fields=[
                (
                    "gameobj_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="boundless.GameObj",
                    ),
                ),
            ],
            options={"abstract": False, "base_manager_name": "objects",},
            bases=("boundless.gameobj",),
        ),
        migrations.CreateModel(
            name="ItemShopStandPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beacon_name",
                    models.CharField(db_index=True, max_length=64),
                ),
                ("guild_tag", models.CharField(max_length=8)),
                ("world", models.CharField(db_index=True, max_length=64)),
                ("item_count", models.IntegerField()),
                ("shop_activity", models.IntegerField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("location_x", models.IntegerField()),
                ("location_y", models.IntegerField()),
                ("location_z", models.IntegerField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boundless.Item",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ItemRequestBasketPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beacon_name",
                    models.CharField(db_index=True, max_length=64),
                ),
                ("guild_tag", models.CharField(max_length=8)),
                ("world", models.CharField(db_index=True, max_length=64)),
                ("item_count", models.IntegerField()),
                ("shop_activity", models.IntegerField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("location_x", models.IntegerField()),
                ("location_y", models.IntegerField()),
                ("location_z", models.IntegerField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boundless.Item",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="item",
            name="item_subtitle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boundless.Subtitle",
            ),
        ),
        migrations.CreateModel(
            name="LocalizedName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(max_length=16, verbose_name="Language"),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Name"),
                ),
                (
                    "game_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boundless.GameObj",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_boundless.localizedname_set+",
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
                "unique_together": {("game_obj", "lang")},
            },
        ),
    ]
