# Generated by Django 3.0.6 on 2020-07-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gui_name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
