# Generated by Django 3.0.6 on 2020-07-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequestbasketprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemshopstandprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
