# Generated by Django 3.0.8 on 2020-07-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundless', '0002_create_item_timeseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='region',
            field=models.CharField(choices=[('use', 'US East'), ('use', 'US West'), ('ecu', 'EU Central'), ('aus', 'Australia'), ('creative', 'Creative')], max_length=16),
        ),
    ]
