# Generated by Django 3.0.10 on 2020-09-12 17:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(db_index=True, help_text='Folder relative to root of game', max_length=128, verbose_name='Folder')),
                ('filename', models.CharField(db_index=True, max_length=64, verbose_name='Filename')),
                ('file_type', models.PositiveSmallIntegerField(choices=[(0, 'JSON'), (1, 'MSGPACK'), (2, 'OTHER')], db_index=True, verbose_name='Source File Type')),
                ('game_version', models.CharField(db_index=True, help_text='Version of the game file was ingest from', max_length=8, verbose_name='Source Game Version')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'unique_together': {('folder', 'filename', 'game_version')},
            },
        ),
    ]
