# Generated by Django 3.1.1 on 2020-09-30 14:58

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_auto_20200912_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamefile',
            name='content',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
