#!/bin/bash

set -o errexit
set -o nounset


rm -f './celerybeat.pid'

if [ -n "${NEW_RELIC_CONFIG_FILE}" ]; then
    echo "Starting with New Relic support..."
    newrelic-admin run-program celery -A config.celery_app beat -l INFO
else
    celery -A config.celery_app beat -l INFO
fi
