#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate

# handle Python syntax errors during development
while true; do
    set +e
    python manage.py runserver 0.0.0.0:8000
    set -e
    sleep 5
done
