# Generated by Django 3.0.8 on 2020-07-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='boundless_account_uid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
