# Generated by Django 3.0.9 on 2020-08-06 00:10

from django.db import migrations
from django.contrib.postgres import operations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        operations.TrigramExtension(),
    ]
