# Generated by Django 3.1.1 on 2020-09-30 14:54

import django.contrib.postgres.operations
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(
        ),
        migrations.RunSQL(
            sql="\nCREATE OR REPLACE FUNCTION _final_median(numeric[])\n   RETURNS numeric AS\n$$\n   SELECT AVG(val)\n   FROM (\n     SELECT val\n     FROM unnest($1) val\n     ORDER BY 1\n     LIMIT  2 - MOD(array_upper($1, 1), 2)\n     OFFSET CEIL(array_upper($1, 1) / 2.0) - 1\n   ) sub;\n$$\nLANGUAGE 'sql' IMMUTABLE;\n\nCREATE AGGREGATE median(numeric) (\n  SFUNC=array_append,\n  STYPE=numeric[],\n  FINALFUNC=_final_median,\n  INITCOND='{}'\n);\n",
            reverse_sql='DROP FUNCTION IF EXISTS _final_median(); DROP AGGREGATE IF EXISTS median();',
        ),
    ]
