# Generated by Django 3.0.9 on 2020-08-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_create_trigram"),
    ]

    operations = [
        migrations.RunSQL(
            (
                """
CREATE OR REPLACE FUNCTION _final_median(numeric[])
   RETURNS numeric AS
$$
   SELECT AVG(val)
   FROM (
     SELECT val
     FROM unnest($1) val
     ORDER BY 1
     LIMIT  2 - MOD(array_upper($1, 1), 2)
     OFFSET CEIL(array_upper($1, 1) / 2.0) - 1
   ) sub;
$$
LANGUAGE 'sql' IMMUTABLE;

CREATE AGGREGATE median(numeric) (
  SFUNC=array_append,
  STYPE=numeric[],
  FINALFUNC=_final_median,
  INITCOND='{}'
);
"""
            ),
            (
                "DROP FUNCTION IF EXISTS _final_median(); DROP AGGREGATE IF EXISTS median();"
            ),
        )
    ]
