# Generated by Django 3.1.8 on 2021-04-29 23:16

from django.db import migrations, models
import storages.backends.azure_storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('description', models.TextField()),
                ('exported_file', models.FileField(storage=storages.backends.azure_storage.AzureStorage(azure_container='local-exports'), upload_to='')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
